#!/bin/sh

echo "0" >loss
echo "0" >delay
echo "0" >delaytol
echo "0" >reorder
echo "0" >corrupt
echo "0" >duplicate

echo "clearing config..."
for file in /sys/class/net/*;
do
  myif=$(basename $file)
  case "$myif" in
    lo)
      continue
    ;;
    eth0)
      continue
    ;;
    *)
      `tc qdisc del dev $myif root netem 2>/dev/null`
    ;;
  esac

done

echo "cleared"

