#!/bin/sh

ifname="eth1"

echo "0" >loss
echo "0" >delay
echo "0" >reorder
echo "0" >corrupt
echo "0" >duplicate

echo "clearing config..."
`tc qdisc del dev $ifname root netem 2>/dev/null`
echo "cleared"

