#!/bin/sh

ifname="eth1"
altif="eth2"
thirdif="eth3"

if [ -f loss ]; then 
    loss=$(cat loss)
else
    loss=0
fi
if [ -f delay ]; then
    delay=$(cat delay)
else
    delay=0
fi
if [ -f delaytol ]; then
    delaytol=$(cat delaytol)
else
    delaytol=0
fi
if [ -f duplicate ]; then
    duplicate=$(cat duplicate)
else
    duplicate=0
fi
if [ -f corrupt ]; then
    corrupt=$(cat corrupt)
else
    corrupt=0
fi
if [ -f reorder ]; then
    reorder=$(cat reorder)
else
    reorder=0
fi
str=""
changed=0

if [ $loss = "0" ]; then
  echo "no loss"
else
  echo "loss is $loss"
  str=$str" loss "$loss"%"
  changed=1
fi

if [ $delay = "0" ]; then
  echo "no delay"
else
  echo "delay is $delay"
  str=$str" delay "$delay"ms"
  if [ $delaytol != "0" ]; then
      echo "delay tolerance is $delaytol"
      str=$str" "$delaytol"ms"
  fi
  changed=1
fi
if [ $duplicate = "0" ]; then
  echo "no duplication"
else
  echo "$duplicate% duplicated packets"
  str=$str" duplicate "$duplicate"%"
  changed=1
fi
if [ $corrupt = "0" ]; then
  echo "no corrupted packets"
else
  echo "$corrupt% corrupted packets"
  str=$str" corrupt "$corrupt"%"
  changed=1
fi
if [ $reorder = "0" ]; then
  echo "no packet reordering"
else
  echo "$reorder% reordered packets"
  str=$str" reorder "$reorder"%"
  changed=1
fi


echo "clearing config..."
`tc qdisc del dev $ifname root netem 2>/dev/null`
`tc qdisc del dev $altif root netem 2>/dev/null`
`tc qdisc del dev $thirdif root netem 2>/dev/null`

echo "setting$str"

if [ $changed = 1 ]; then
#  echo "tc qdisc add dev $ifname root netem$str"
  `tc qdisc add dev $ifname root netem$str`
  `tc qdisc add dev $altif root netem$str`
  `tc qdisc add dev $thirdif root netem$str`
fi
echo "done."
